### PR TITLE
added acct-group plugdev

### PR DESCRIPTION
**Pull request by Katana-Steel**
the plugdev groupid was set to that of one of my Debian installs, 
and it seemed to not conflict with any other group ids

### CODE REVIEW

**Comment by cjmayo** [comment]
Thanks - I could have been clearer, I meant "submit to gentoo-dev mailing list and get it accepted". If we use it before that we end up with a solaar ebuild that definitely can't be merged (although as it is maintainer-wanted I'm not expecting too much). Anyway, not wasted work `git send-email` is the way to go.
I can't comment on the detail of the plugdev ebuild, but looks like there is one too many blank lines before the EAPI=7.

**Comment by Katana-Steel** [comment]
no worries, 
I think the extra lines only matter for ascetics,
there's no functional difference.

I won't mind reformatting it if needed be...

**Comment by cjmayo** [comment]
Updated the Gentoo PR now that acct-group/plugdev is available (N.B. don't need pkg_postinst() at all now).

**Comment by Katana-Steel** [comment]
nice, thank you for taking the time to look it over

**Pull request closed without merging**
